services:
  - type: web
    name: n8n-server
    env: docker
    repo: https://github.com/codewithpanda28/n8n-email-to-whatsapp-bot
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: WEBHOOK_URL
        value: https://sarkari-job-alerts-q4tc.onrender.com/webhook-test/form
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: akashkumar.webdev@gmail.com
      - key: N8N_BASIC_AUTH_PASSWORD
        value: ak123456789.?
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
