services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: WEBHOOK_TUNNEL_URL
        value: https://primary-production-7c06.up.railway.app/webhook/757eee0e-9b15-4cf8-a808-39af78eaae58
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
